controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

switch_language:
    path: /switch-language/{locale}
    controller: App\Controller\LanguageController::switchLanguage